apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: destiny-viewer

resources:
  - namespace.yaml
  - backend-secret.yaml
  - backend-pvc.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
